import Link from 'next/link';
import { ArrowUpRight, Check, Download, FileText, GitBranch, ShieldCheck } from 'lucide-react';
import { SiteHeader } from '@/components/site-header';
import { Workflow } from '@/components/workflow';

const skills = ['tech-research-work', 'research-resources', 'build-evidence-context', 'write-blog', 'edit-blog', 'review-blog', 'write-linkedin', 'write-x', 'create-content'];
const telegramPostBotDownload = 'https://github.com/omidakhavans/Telegram-Post-Bot/releases/latest/download/telegram-post-bot.zip';

export default function HomePage() {
  return <main>
    <div className="grid-bg border-b border-black/10 dark:border-white/10"><SiteHeader /><section className="mx-auto grid max-w-6xl gap-12 px-5 pb-24 pt-20 lg:grid-cols-[1.15fr_.85fr] lg:px-8 lg:pt-28"><div><p className="mb-6 font-mono text-xs uppercase tracking-[.24em] text-electric">Phase 1 · Codex Skills</p><h1 className="max-w-3xl text-5xl font-semibold leading-[1.02] tracking-[-.06em] sm:text-7xl">Technical content with an evidence trail.</h1><p className="mt-7 max-w-2xl text-lg leading-8 text-slate-600 dark:text-slate-300">tech-content-agent turns engineering work into grounded, reviewable content through small skills and explicit Markdown artifacts.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/docs" className="inline-flex items-center gap-2 bg-ink px-5 py-3 text-sm font-semibold text-white hover:bg-electric">Read the docs <ArrowUpRight size={16}/></Link><a href="https://github.com/omidakhavans/tech-content-agent" className="inline-flex items-center gap-2 border border-black/15 px-5 py-3 text-sm font-semibold hover:border-black/40 dark:border-white/20 dark:hover:border-white/50">View source <GitBranch size={16}/></a><a href={telegramPostBotDownload} className="inline-flex items-center gap-2 border border-black/15 px-5 py-3 text-sm font-semibold hover:border-black/40 dark:border-white/20 dark:hover:border-white/50"><Download size={16}/> Download Telegram Post Bot</a></div></div><div className="self-end border border-black/10 bg-white/70 p-5 shadow-line dark:border-white/10 dark:bg-[#151820]/80"><div className="mb-5 flex items-center justify-between border-b border-black/10 pb-4 font-mono text-xs text-slate-500 dark:border-white/10"><span>content-run-summary.md</span><span className="text-electric">ready_for_human_review</span></div><div className="space-y-3 font-mono text-sm"><p><span className="text-slate-400">$</span> use $create-content</p><p className="pl-5 text-slate-500">subject: “what we learned shipping…”</p><p className="flex items-center gap-2 text-emerald-700 dark:text-mint"><Check size={15}/> research-report.md</p><p className="flex items-center gap-2 text-emerald-700 dark:text-mint"><Check size={15}/> context-brief.md</p><p className="flex items-center gap-2 text-emerald-700 dark:text-mint"><Check size={15}/> blog-review.md</p><p className="flex items-center gap-2 text-slate-500"><span className="h-3.5 w-3.5"/> human review required</p></div></div></section></div>
    <section className="mx-auto max-w-6xl px-5 py-24 lg:px-8"><div className="max-w-2xl"><p className="font-mono text-xs uppercase tracking-[.2em] text-electric">The premise</p><h2 className="mt-4 text-3xl font-semibold tracking-[-.04em] sm:text-5xl">Writing is the last step, not the first.</h2><p className="mt-5 leading-7 text-slate-600 dark:text-slate-300">The workflow separates local work evidence, external resources, context selection, generation, evaluation, and platform-specific transformation. Each stage leaves an artifact another person—or another agent—can inspect.</p></div><div className="mt-14"><Workflow/></div></section>
    <section className="border-y border-black/10 bg-white dark:border-white/10 dark:bg-[#151820]"><div className="mx-auto grid max-w-6xl gap-16 px-5 py-24 lg:grid-cols-[.8fr_1.2fr] lg:px-8"><div><p className="font-mono text-xs uppercase tracking-[.2em] text-electric">Current capabilities</p><h2 className="mt-4 text-3xl font-semibold tracking-[-.04em]">Small contracts. Composable stages.</h2><p className="mt-5 leading-7 text-slate-600 dark:text-slate-300">The project is intentionally runtime-light. Codex is the runtime; the repository defines the interfaces and the artifact conventions.</p></div><div className="grid gap-3 sm:grid-cols-2">{skills.map((skill) => <Link key={skill} href={`/docs/skills/${skill}`} className="group flex items-center justify-between border border-black/10 px-4 py-4 font-mono text-sm hover:border-electric dark:border-white/10"><span>{skill}</span><ArrowUpRight size={15} className="text-slate-400 transition group-hover:text-electric"/></Link>)}</div></div></section>
    <section className="mx-auto max-w-6xl px-5 py-24 lg:px-8"><div className="grid gap-5 md:grid-cols-3">{[[ShieldCheck,'Evidence before prose','Claims stay traceable to source code, commits, docs, and supplied resources.'],[FileText,'Markdown as the interface','Artifacts are plain files under .techcontent, easy to review, diff, and reuse.'],[GitBranch,'Human in the loop','The pipeline stops at quality gates and never publishes or calls social APIs.']].map(([Icon,title,text]) => { const I = Icon as typeof ShieldCheck; return <div key={title as string} className="border-t-2 border-ink pt-5 dark:border-mint"><I size={21}/><h3 className="mt-6 font-semibold">{title as string}</h3><p className="mt-2 text-sm leading-6 text-slate-600 dark:text-slate-400">{text as string}</p></div>})}</div></section>
    <footer className="border-t border-black/10 dark:border-white/10"><div className="mx-auto flex max-w-6xl flex-col gap-4 px-5 py-8 text-sm text-slate-500 sm:flex-row sm:items-center sm:justify-between lg:px-8"><span>tech-content-agent · Phase 1 prototype</span><div className="flex gap-5"><Link href="/docs" className="hover:text-ink dark:hover:text-white">Documentation</Link><a href="https://github.com/omidakhavans/tech-content-agent" className="hover:text-ink dark:hover:text-white">GitHub</a></div></div></footer>
  </main>;
}
